### ISSUE TITLE
Load additional songs?

### ISSUE THREAD

**Issue by jvalal** [agtokty/heardle-turkish#1]
Hello - I just forked this trying to replicate. How do I change the song?

**Comment by agtokty** [comment]
What do you mean by changing song? If you refer to daily songs, you can use your own firebase database to fetch songs but I need to share the structure of database with a sample data in it for the songs.

**Comment by jvalal** [comment]
I'm unsure how to create and structure a firebase database to fetch songs.
Is that something you can demonstrate on how to do?

**Comment by anothergithubuser69** [comment]
i have the same problem. Could you show how you have structured the database?

**Comment by agtokty** [comment]
Hi @jvalal, @anothergithubuser69 here is the current structure but I am planning to make it simpler,  I will update readme then.

```
{
  "songs" : { //root
    "2022" : {// year
      "04" : { // month number
        "06" : {// day number
          "artist" : "<ArtistName>", // optional
          "breaks" : [ 2, 6, 15, 20, 30, 40 ], //game step intervals
          "day" : "20220407", // optional
          "others" : ["<SongName-ArtistName>", "<ArtistNameAlternative-SongName>", ... ], // alternative values to check user inputs
          "song" : "<SongName>",// optional
          "songLength" : 40, //should be same with last break value
          "soundCloudLink" : "<Soundcloud-Link>", // soundcloud song link
          "soundSpotifyLink" : "https://open.spotify.com/embed/track/<SongId>", //spotify song embebed link
          "trackName" : "<ArtistName-SongName>" // first value to check user inputs
        },
        "07": { 
             //....
          }
      }
    }
  }
}

```

**Comment by agtokty** [comment]
@jvalal you can import this file to your firebase firestore database (save as json file and change the month-day numbers to able test)
[import.txt](https://github.com/agtokty/heardle-turkish/files/8432750/import.txt)

**Comment by jvalal** [comment]
I've never implemented a firebase DB, so I'm unsure of the steps to do so. Is this easy?
