### ISSUE TITLE
sharing date/paylaşım tarihi

### ISSUE THREAD

**Issue by bL00keRs** [agtokty/heardle-turkish#2]
hello, when sharing, twitter does not share if it is the same as the previous tweet, because it does all of them with the same text. Can the date of the day be added to the posts? / merhabalar, paylaşımı yaparken hepsini aynı metinle yaptığı için twitter önceki twitle aynıysa paylaşım yaptırmıyor. paylaşımlara günün tarihi eklenebilir mi?

**Comment by agtokty** [comment]
hi, I appreciate you taking the time to suggest that feature. done👍🏻
